function [fitresult, gof] = createFits(xx, yy)
%CREATEFITS(XX,YY)
%  Create fits.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xx
%      Y Output: yy
%  Data for 'untitled fit 2' fit:
%      X Input : xx
%      Y Output: yy
%  Data for 'untitled fit 3' fit:
%      X Input : xx
%      Y Output: yy
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Aug-2018 17:20:47

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 3, 1 );
gof = struct( 'sse', cell( 3, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xx, yy );

% Set up fittype and options.
ft = fittype( 'a*sin(x)*(1-exp(b))/(1-cos(x)*exp(b))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 -1];
opts.StartPoint = [0.959492426392903 0.655740699156587];
opts.Upper = [100000 0];

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult{1}, xData, yData );
legend( h, 'yy vs. xx', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel xx
ylabel yy
grid on

%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( xx, yy );

% Set up fittype and options.
ft = fittype( 'a*x*(1+b/2)/(1+b/2+x^2/2/b)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0];
opts.StartPoint = [0.0117211345891028 0.505112222971969];
opts.Upper = [100000 1];

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 2' );
h = plot( fitresult{2}, xData, yData );
legend( h, 'yy vs. xx', 'untitled fit 2', 'Location', 'NorthEast' );
% Label axes
xlabel xx
ylabel yy
grid on

%% Fit: 'untitled fit 3'.
[xData, yData] = prepareCurveData( xx, yy );

% Set up fittype and options.
ft = fittype( 'a*x*(1+b/2)/(1+b/2+x^2/2/b)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.0801067479396441 0.0707229182941546];

% Fit model to data.
[fitresult{3}, gof(3)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 3' );
h = plot( fitresult{3}, xData, yData );
legend( h, 'yy vs. xx', 'untitled fit 3', 'Location', 'NorthEast' );
% Label axes
xlabel xx
ylabel yy
grid on


